// <auto-generated />
namespace ManagementDelivery.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ConfigNotNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConfigNotNull));
        
        string IMigrationMetadata.Id
        {
            get { return "201903201354090_ConfigNotNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
